### ISSUE TITLE
Tutorials/Examples are broken

### ISSUE THREAD

**Issue by ezavod** [chemfiles/chemfiles.py#17]
Simply wanted to generate some structures for testing by using the [corresponding tutorial](https://chemfiles.org/chemfiles.py/latest/tutorials.html#generating-a-structure).
Got the following errors:

- `AttributeError: 'Topology' object has no attribute 'add_atom'`
Replace `topology.add_atom(Atom("H"))` with `topology.atoms.append(Atom("H"))`
- `AttributeError: 'Frame' object has no attribute 'set_topology'`
Replace `frame.set_topology(topology)` with `frame.topology = topology`
- `TypeError: 'numpy.ndarray' object is not callable`
Replace `positions = frame.positions()` with `positions = frame.positions`
- `AttributeError: 'Frame' object has no attribute 'set_cell'`
Replace `frame.set_cell(UnitCell(10, 10, 10))` with `frame.cell = UnitCell(10, 10, 10)`
- The output file is still empty after all those changes...
Call `trajectory.close()`

chemfiles (0.9.1) via pip
Python 3.7.3

**Comment by Luthaf** [comment]
Whoops ... Thanks for the report!

**Comment by ezavod** [comment]
Maybe one could think of a way to add the examples as some sort of tests, so whenever new changes are pushed the examples are tested as well.
Since chemfiles offers bindings for such an awesome variety off different language it's really hard to manually keep track of everything :)

**Comment by Luthaf** [comment]
> Maybe one could think of a way to add the examples as some  sort of tests, so whenever new changes are pushed the examples are  tested as well.

Great idea =)
