### ISSUE TITLE
Add python 3.10 support

### ISSUE THREAD

**Issue by IAlibay** [chemfiles/chemfiles.py#39]
This is possible more related to the conda-forge feedstock, but raising it here since I'm not seeing py3.10 on CI.

It'd be awesome if we could get a py3.10 conda build for chemfiles.

**Comment by Luthaf** [comment]
I'm looking into the conda-forge build (https://github.com/conda-forge/chemfiles-python-feedstock/pull/23). In the mean time, the PyPI version should be available for any python version.
