### ISSUE TITLE
[chemfiles 0.10.4] Cannot find libchemfiles.dll

### ISSUE THREAD

**Issue by IAlibay** [chemfiles/chemfiles.py#50]
Windows CI on MDAnalysis is failing with:

Could not find module 'C:\hostedtoolcache\windows\Python\3.11.3\x64\Lib\site-packages\chemfiles\libchemfiles.dll' (or one of its dependencies). 

when installing with the newly uploaded pypi release for v0.10.4

**Comment by Luthaf** [comment]
Sorry about that. I moved from custom code to build wheels to cibuildwheels, and it looks like the wheel got built with MingGW compilers instead of GCC =/ I'll pull the wheel out of PyPI and check how to fix this.
